# Generated by Django 2.2.4 on 2020-05-07 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookfile',
            name='size',
        ),
        migrations.AddField(
            model_name='bookfile',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
