# Generated by Django 2.2.4 on 2020-05-07 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20200507_1035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookfile',
            name='info',
        ),
        migrations.AddField(
            model_name='bookfile',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='books.Author'),
        ),
        migrations.AddField(
            model_name='bookfile',
            name='genres',
            field=models.ManyToManyField(null=True, to='books.BookGenre'),
        ),
        migrations.AddField(
            model_name='bookfile',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bookfile',
            name='publish_year',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='BookInfo',
        ),
    ]
