# Generated by Django 3.0.8 on 2020-10-10 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20200507_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookfile',
            name='size',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
