# Generated by Django 3.0.8 on 2020-12-19 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_bookfile_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookgenre',
            name='verbose_name',
            field=models.CharField(max_length=200, null=True, verbose_name='Название (человеко-читаемое)'),
        ),
        migrations.AlterField(
            model_name='bookgenre',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название (параметр для авто заполнения жанра из файла)'),
        ),
    ]
